apiVersion: v1
kind: Pod
metadata:
  name: node-app
  namespace: gs2e-training
  labels:
    app: node
    env: dev
spec:
  containers:
  - name: node
    image: basska/node-app:v1
    env:
    - name: APP_NAME
      value: "node-gs2e-app"
    volumeMounts:
    - name: app-storage
      mountPath: /data
  volumes:
    - name: app-storage
      persistentVolumeClaim:
        claimName: node-app-pvc