apiVersion: v1
kind: PersistentVolume
metadata:
  name: node-app-pv
  labels:
    env: dev
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: web-class
  hostPath:
    path: /data/gs2e-pv-vol