apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: node-app-pvc
  namespace: gs2e-training
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: web-class
  selector:
    matchLabels:
      env: dev