apiVersion: v1
kind: Pod
metadata:
  name: node-app-front
  namespace: gs2e-training
  labels:
    app: node
    env: dev
    tier: front
spec:
  containers:
  - name: node
    image: basska/node-app:v2
    command: ["node", "server-front.js"]
    env:
    - name: API_URL
      value: "node-app-service.gs2e-training.svc.cluster.local"
